### ISSUE TITLE
SD readers zie ik alleen maar in de documentatie

### ISSUE THREAD

**Issue by sandervandorsten** [Swendude/kwhm-library#4]
SD reader staat alleen in de documentatie, niet in de code?

**Let op! SDPIN om te connecten moet op 10. **

`sdpin = 10` <dit is de CS pin! staat normaal op 4, alleen daar zit nu een toetsenbord

**Comment by Swendude** [comment]
Net gepushed, mijn fout. Je bedoelt de ss pin? Dat is volgens mij SCK op de ICSP header.
