### ISSUE TITLE
speaker functie mist

### ISSUE THREAD

**Issue by sandervandorsten** [Swendude/kwhm-library#6]
ookal is het alleen tone (x,y ,z), wel even documentatie schrijven

**Comment by sandervandorsten** [comment]
moet namelijk ook weer de tone uitzetten, en een delay aanhouden voor de toonduratie.

voorbeeld: (pin `14` is analoge pin A0)
```
  tone(14, 440, 3000);
  Serial.println("hoi");
  delay(3000);
  noTone(14);
```

**Comment by Swendude** [comment]
Toegevoegd.
